# frozen_string_literal: true

source "https://rubygems.org"

gem "anthropic", "~> 1.23.0"
gem "base64"
gem "logger"
gem "opentelemetry-sdk"
gem "opentelemetry-instrumentation-anthropic"
gem "opentelemetry-instrumentation-net_http"
