flowchart LR
    START[ログレコード<br/>が渡る] --> cond1{ハンドラの<br/>レベル以上の<br/>呼び出しか};
    cond1 -->|はい<br/>=有効| cond2[ハンドラの<br/>フィルタは<br/>却下するか];
    cond1 -->|いいえ<br/>| END[停止];
    cond2 -->|いいえ<br/>=通過| node1[排出（フォーマッタ込み）];
    cond2 -->|はい<br/>| END[停止];
