flowchart LR
    START[Logging<br/>call] -->|"e.g.<br/>logger.info(...)"| cond1{Logger enabled for<br/>level of call?};
    cond1 -->|yes<br/>= enabled| node1[Create<br/>LogRecord];
    node1 --> node2[Pass to handlers<br/>of current logger];
    node2 --> cond3{Is propagate True<br/>for current logger?};
    cond3 -->|yes=true<br/>= propagate| cond4{Is there<br/>a parent logger?};
    cond4 -->|yes=parent<br/>exists| node3[Set current logger<br/>to parent];
    node3 --> node2;
