flowchart LR
    START[LogRecord<br/>passed] --> cond1{Handler enabled for<br/>level of record?};
    cond1 -->|yes<br/>= enabled| cond2[Does a filter attached<br/>to handler reject the record?];
    cond1 -->|no| END[Stop];
    cond2 -->|no<br/>= pass| node1["Emit<br/>(includes formatting)"];
    cond2 -->|yes| END[Stop];
